import type {Metadata} from "next";
import {Inter as FontSans} from "next/font/google";

import {cn} from "@/lib/utils";
import ProjectFilterBar from "@/components/Project/ProjectFilterBar";
import Heading from "@/components/Heading";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({children}: { children: React.ReactNode }) {
  return (
    <div>
      <Heading
        heading="Projects"
        subheading="I like building things. Here are a few things I've built"
      />
      <ProjectFilterBar/>
      {children}
    </div>
  );
}
