import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google"
import "./globals.css";

import { cn } from "@/lib/utils"
import { Header } from "@/components/Header/index";
import Tab from "@/components/Header/Tab";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "flex flex-col min-h-screen w-screen bg-background font-sans antialiased items-center",
          fontSans.variable
        )}
      >
        <header className="fixed w-screen md:w-2/3 mt-4 md:mt-10">
          <Tab />
        </header>
        <main className="w-screen md:w-2/3">{children}</main>
      </body>
    </html>
  );
}
