import type {Metadata} from "next";
import {Inter as FontSans} from "next/font/google"
import "./globals.css";

import {cn} from "@/lib/utils"
import Tab from "@/components/Header/Tab";
import {QueryClient} from "@tanstack/query-core";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body
      className={cn(
        "flex flex-col min-h-screen bg-background font-sans antialiased items-center pb-10",
        fontSans.variable
      )}
    >
    <header className="z-50 fixed top-4 md:top-10 w-[98vw] md:w-2/3">
      <Tab/>
    </header>
    <main className="w-screen md:w-2/3 px-4 md:px-0 pt-20 md:pt-28">{children}</main>
    </body>
    </html>
  );
}
