import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google"
import "@/styles/globals.css";
// core styles shared by all of react-notion-x (required)
import 'react-notion-x/src/styles.css'
// used for code syntax highlighting (optional)
import 'prismjs/themes/prism-tomorrow.css'
// used for rendering equations (optional)
import 'katex/dist/katex.min.css'
// notion custom css
// import "@/styles/notion.css"


import { cn } from "@/lib/utils"
import Tab from "@/components/Tab";
import Footer from "@/components/Footer";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "flex flex-col min-h-screen bg-background font-sans antialiased items-center",
          fontSans.variable
        )}
      >
        <header className="z-50 fixed top-4 md:top-10 transform -translate-x-1/2 left-1/2 md:w-auto">
          <Tab />
        </header>
        <main className="flex-grow w-screen md:w-2/3 px-4 md:px-0 pt-20 md:pt-28">{children}</main>
        <footer>
          <Footer />
        </footer>
      </body>
    </html>
  );
}
